document.write('<header tabindex="0" ><a href="index.html"><img src="images/logo_resized.png" alt="logo"></a></header>');
document.write('		<div id="nav-container">');
document.write('			<div class="button" tabindex="0" >');
document.write('				<span class="icon-bar"></span>');
document.write('				<span class="icon-bar"></span>');
document.write('				<span class="icon-bar"></span>');
document.write('			</div>');
document.write('			<div id="nav-content" tabindex="0" >');
document.write('				<nav class=\'animated bounceInDown\'>');
document.write('					<div class="image">');
document.write('						<img src="images/logo.png" alt="logo">');
document.write('					</div>');
document.write('					<ul>');
document.write('						<li class=\'sub-menu\'><a href=\'index.html\'>Kaart</a>');
document.write('');
document.write('');
document.write('						</li>');
document.write('						<li class=\'sub-menu\'><i class="fas fa-angle-right"></i><a href=\'#message\'>Kohad</a>');
document.write('');
document.write('							<ul>');
document.write('								<li><a href=\'kool.html\'>Kool</a></li>');
document.write('								<li><a href=\'ööelu.html\'>Ööelu</a></li>');
document.write('								<li><a href=\'sport.html\'>Sport</a></li>');
document.write('								<li><a href=\'toit.html\'>Toit</a></li>');
document.write('							</ul>');
document.write('');
document.write('						</li>');
document.write('					');
document.write('');
document.write('');
document.write('');
document.write('');
document.write('');
document.write('');
document.write('');
document.write('					</ul>');
document.write('				</nav>');
document.write('			</div>');
document.write('			');
document.write('		</div>');
